#+BLOG: blog.infotics.es
#+CATEGORY: calendario, evento, periodismodatos, datajournalism 
#+TAGS: boletín, periodismodatos, tinyletter, 
#+DESCRIPTION: Calendario de eventos relacionados con el conocimiento abierto para 2016
#+TITLE: Agenda de Open Knowledge España 2016
#+OPTIONS:  num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
Bienvenidxs a la agenda de eventos relacionados o de interés para la comunidad del conocimiento abierto España.

Si tienes un evento que proponer, añade [[https://github.com/OKFN-Spain/agenda/issues/new][una nueva issue]].

#+TOC: headlines 2

* Enero
** Madrid Python: Aplicaciones avanzadas de /Scraping/
- Cuándo: <2016-01-13 mié>
- URL: http://www.meetup.com/es-ES/Madrid-Python-Meetup/events/227936864/
** Grupo R de Madrid
- Cuándo: <2016-01-14 jue 19:00-20:45>
- Dónde: Medialab Prado, Plaza de las Letras, C/ de la Alameda, 15 , Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://www.meetup.com/es-ES/Grupo-de-Usuarios-de-R-de-Madrid/events/227983479/

*** Introducción a las Redes Neuronales
Francisco Rodríguez hará una introducción a las redes neuronales con R. Las redes neuronales vuelven a ser un campo de intensa actividad de investigación con la aparición de las nuevas topologías de red utilizadas en "Deep Learning".
*** Calidad del aire de Madrid
Carlos Ortega, a partir de los datos del propio Ayuntamiento de Madrid, mostrará un conjunto de análisis sobre cómo de saludable es el aire que respiramos.
*** Price Sensitivity Meter (PSM) in R
Karel Rodriguez mostrará cómo R se puede aplicar para crear una aplicación de uso empresarial que permite determinar el precio óptimo de compra utilizando percepciones psicológicas.

** MadridJS: Taller de programación funcional
- Cuándo: <2016-01-16 sáb 10:00-14:00>
- Dónde: Campus Madrid, Calle Manzanares, 1, Madrid.
- Mapa: http://www.openstreetmap.org/way/7648766
- URL: http://www.meetup.com/es-ES/madridjs/events/227302060/

De la mano de Javier Vélez, profesor de la UNED y co-organizador de MadridJS, aprenderemos a usar técnicas funcionales con JavaScript.

En este taller nos centraremos en abordar los elementos esenciales de la programación funcional tratando de describir como es la algoritmia funcional de una manera comparada en relación a la imperativa. Revisaremos los principios de diseño fundamentales, la ausencia de estado, la transparencia referencial, la inmutabilidad, etc. Estudiaremos recursividad y diseño funcional por inmersión, orden superior y compositividad, evaluación parcial y currificación, abstracciones de datos funcionales, streams y apis fluidas y lo que el tiempo nos permita... Todo ello nos proporcionará las skills necesarias para entender qué es exactamente una solución funcional, que la distingue de otras aproximaciones y nos preparará sin duda para hacer frente al emergente reto de las arquitecturas reactivas que se imponen como una realidad actual. 

** X Machine Learning Spain
- Cuándo: <2016-01-18 lun 18:30-20:30>
- Dónde: Campus Madrid, Calle Manzanares, 1, Madrid
- Mapa: http://www.openstreetmap.org/way/7648766
- URL: http://www.meetup.com/es-ES/MachineLearningSpain/events/227206352/

*** Pragmatic ML

How can you ensure that your work and use of ML gets the most impact in the domain you apply it to? From collaborating with all stake-holders to simulating how predictions will really be used, evaluating them domain-side and deploying models at scale in production, I’ll share some of the lessons I’ve learnt when it comes to integrate ML in real-world applications. Also, I’ll review some research problems and new open source software aimed at making it easier to create, experiment with, and operationalise predictive models.

Louis Dorard I'm the author of Bootstrapping Machine Learning, the first guide to Predictive APIs, and a co-founder of PAPIs.io­, the world's first conference on Predictive APIs and Predictive Apps. My goal is to help people use new machine learning technologies to make their apps and businesses smarter. I do this by writing, speaking and teaching.

*** Sistemas Cognitivos Artificiales: cuando aprender no es suficiente

Las técnicas de aprendizaje automático a menudo tratan de imitar la capacidad que poseen muchos organismos biológicos para adaptarse y progresar en su ecosistema, ¿pero es el aprendizaje la única clave de su adaptación? ¿Qué más capacidades cognitivas requieren los organismos para competir en entornos complejos y desestructurados? En esta charla adoptaremos un enfoque amplio de la cognición desde el punto de vista de la neuropsicología cognitiva, poniendo foco en nuevas aplicaciones empresariales y las tecnologías que las pueden hacer posibles.

Raúl Arrabales es ingeniero en informática, doctor en Inteligencia Artificial y MBA. En los últimos años ha liderado proyectos y startups de base tecnológica asumiendo diferentes roles, desde Jefe de Proyecto a CEO, en compañías como IBM, ARRIS, T-Online, Comaware y Altran. En el ámbito científico, contribuye al avance de las Ciencias Cognitivas con nuevos modelos computacionales.
También imparte clases y conferencias de Informática, Inteligencia Artificial, Inteligencia de Negocio, Robótica y Sistemas Cognitivos en diferentes centros, habiendo sido Profesor Doctor de la Universidad Carlos III de Madrid, Director del área de ingeniería en U-tad (Universidad Camilo José Cela) y director académico de MBiT School. Actualmente Raúl es Analytics Senior Manager en Accenture Digital. 


** Journocoders Madrid meets BBC API
- Cuándo: <2016-01-19 mar 18:45-20:30>
- Dónde: Medialab Prado, Plaza de las Letras, C/ de la Alameda, 15 , Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://s.coop/apibbc

Primero haremos un show&tell con los enlaces recomendados de #periodismodatos. Luego seguimos un tutorial muy básico sobre cómo trabajar con API. Para ello, utilizaremos la herramienta desarrollada por BBC News Labs: News Juicer API. Esta API permite acceder a los artículos en diferentes idiomas de más de 400 medios en todo el mundo. 

** Java vs Node.js: el encuentro
- Cuándo: <2016-01-19 mar>
- Dónde: Campus Madrid, Calle Manzanares, 1, Madrid
- Mapa: http://www.openstreetmap.org/way/7648766
- URL: http://www.meetup.com/es-ES/Node-js-Madrid/events/226495441/

Vamos a hacer una mesa redonda entre dos comunidades muy distintas en apariencia pero no tanto en la práctica: Java y Node.js. Moderada por el gran David Bonilla (@david_bonilla),  CEO de Otogami, y con los siguientes ponentes de lujo asiático:

- Javier Vélez (@javiervelezreye)
- Javier Abadía @javierabadia
- Pedro Palao
- Micael Gallego: @micael_gallego https://about.me/micael.gallego
- Leo Antoli (@lantoli) http://nextail.co
- Nacho Coloma (@nachocoloma) 

¿Qué podemos aprender unos de otros? ¿En qué nos parecemos y en qué nos diferenciamos? Entre otras cosas, hablaremos de:

- Tipado fuerte vs tipado débil.
- Productividad.
- Rendimiento: bruto y de entrada/salida.
- Soporte enterprise.
- Y los que salgan.

¿Te vas a perder el evento de moda en el nuevo año? 
** /D3.js Madrid/: introducción a /D3.js/ y creación de /dashboard/ con /DC.js/
- Cuándo: <2016-01-27 mié 19:30-20:30>
- Dónde: Oficinas de ShuttleCloud, Ronda de Atocha, 37 Oficina Derecha 28012, Madrid
- Mapa: http://www.openstreetmap.org/node/3423331185
- URL: http://www.meetup.com/es-ES/Madrid-D3-js/events/228011001

Segundo Meetup de [[http://www.meetup.com/es-ES/Madrid-D3-js/][D3.js Madrid]] con un par de charlas:

- Introducción a [[http://d3js.org][D3.js]] por [[https://twitter.com/maritrinez][Beatriz Martínez]]
- Crear un dashboard con [[https://dc-js.github.io/dc.js/][DC.js]], por [[https://twitter.com/ferblape][Fernando Blat]]

Se trata de dos charlas de 30 minutos de duración. Para la primera no hace falta ningún conocimiento previo de D3, mientras que para la segunda se darán por sabidos algunos conceptos. La idea es poder llegar tanto a gente que no conoce la librería como a gente que ya se ha peleado con ella y quiere profundizar en algún tema.

Así que animaros aunque no hayáis utilizado D3 nunca.

PD: por cierto, si te animas a dar una charla en futuras ediciones no dudes en decírnoslo. Queremos mantener el formato de dos charlas cortas, una introductoria y otra algo más avanzada.

* Febrero
** II Aniversario Data Science Spain
- Cuándo: <2016-02-04 jue>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://www.meetup.com/es-ES/Data-Science-Spain/events/227690627/

El próximo 4 de febrero DATA SCIENCE SPAIN cumple 2 AÑOS y queremos celebrarlo realizando el primer encuentro de 2016 con todos vosotros!!

Abrimos como siempre un call4papers para que podáis presentar vuestras ideas de charlas mandando un mail a cmartinez@synergicpartners.com
** Grupo R de Madrid
- Cuándo: <2016-02-11 jue 19:00-20:45>
- Dónde: Medialab Prado, Plaza de las Letras, C/ de la Alameda, 15 , Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://www.meetup.com/es-ES/Grupo-de-Usuarios-de-R-de-Madrid/events/228578129/

*** Programa:
- Gabriel Antonio Valverde Castilla: Introducción al "Deep Learning"
- Carlos J. Gil Bellosta: Modelos Estadísticos usando "rstan", interfaz R a Stan, el lenguaje que permite la creación y determinación de modelos estadísticos.
- Manuel García: "Artificial Bee Colony (ABC) Optimization" (paquete "ABCoptim"), optimización de funciones basado en agentes que simulan el comportamiento de una colonia de abejas.

** El periodista como analista de datos masivos
- Cuándo: <2016-02-17 mié 18:30-20:30>
- Dónde: Medialab Prado, Plaza de las Letras, C/ de la Alameda, 15 , Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://www.meetup.com/es-ES/Madrid-Periodismo-de-datos-Meetup/events/228690087/ y http://medialab-prado.es/article/analisis-de-datos-masivos-con-talend-open-studio
- Organizado por: Grupo de #periodismodatos de Medialab-Prado, /Journocoders Madrid/

El 17 de febrero alcanzamos las 28 sesiones y celebramos el día del amor por el software libre (#ILOVEFS) con un reto que afrontaremos entre todxs: la herramienta libre Talend Open Studio de la mano de Rigo, analista de datos del ICIJ, Consorcio Internacional de Periodistas de Investigación y que está acostumbrado a trabajar con grandes volúmenes de datos en proyectos periodísticos de primerísima fila como /Offshore Leaks/.

Imaginaos un programa que es capaz de cargar distintas archivos de datos de distintas fuentes, de realizar transformaciones a los datos como lo haríais con Refine, de mezclar esos datos e insertarlos en una base de datos y mostrara el resultado final con un informe del proceso. Ese es un ejemplo de lo que se puede hacer con Talend Open Studio y las herramientas ETL. 

** ALLDATA 2016: Second International Conference on Big Data, Small Data, Linked Data and Open Data
- Cuándo: <2016-02-21 dom>--<2016-02-25 jue>
- Dónde: Lisboa, Portugal
- URL: http://www.iaria.org/conferences2016/ALLDATA16.html

* Marzo
** Presentación informe España en Gobierno Abierto, 2013-2014
- Cuándo: <2016-03-01 mar 19:00-20:30>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/presentacion-informe-de-espana-en-gobierno-abierto-2013-2014
- Streaming: http://medialab-prado.es/article/streaming

España forma parte de la Alianza para el Gobierno Abierto desde 2011, iniciativa que integra a casi 70 países del mundo y cuyo propósito es compartir experiencias y desarrollar un foro permanente para avanzar hacia una mayor transparencia pública, combatir la corrupción con apertura de datos, incentivar la participación ciudadana y fortalecer los sistemas de control social y rendición pública de cuentas a través de las nuevas tecnologías.

El informe se realiza bajo una metodología común para todos los países participantes y recoge los hallazgos principales del avance de España en Gobierno Abierto. La información gubernamental se contrasta con las valoraciones y hallazgos de OSC implicadas con la transparencia y el gobierno abierto en España, ofrece argumentos críticos a la vez que propuestas constructivas, y detalla el avance y los retos de desarrollo de los 10 compromisos incluidos en el segundo plan de acción, siendo el compromiso más importante el lanzamiento del Portal de la Transparencia de la Administración General del Estado.

Este informe ha sido realizado por el Investigador del [[http://www.gigapp.org][GIGAPP]] (Grupo de Investigación en Gobierno, Administración y Políticas Públicas), Dr. César Nicandro Cruz-Rubio ([[https://twitter.com/cesarncruz][@cesarncruz]]). 

*** Invitados especiales:

- Dña. Victoria Anderica. Experta en transparencia y gobierno abierto. Responsable del área de Transparencia. Ayuntamiento de Madrid
- Dña. Victoria Figueroa. Directora de la Oficina de Transparencia y Acceso a la Información. Ministerio de la Presidencia 

** Circumvention Tech Festival
- Cuándo: <2016-03-01 mar>--<2016-03-06 dom>
- Dónde: Las Naves, Carrer de Joan Verdeguer 16, Valencia, España
- Mapa: http://www.openstreetmap.org/way/158789093#map=19/39.45850/-0.33798
- URL: http://www.circumventionfestival.es/

Se han registrado profesionales de 47 países diferentes y contamos con la participación de organizaciones como Tor, Electronic Frontier Foundation, Freedom of the Press Foundation, Xnet, Tactical Tech, Global Voices, Filtra.la, APC, Mozilla Foundation y muchas más.

** Carving Up Legacy with Microservices
- Cuándo: <2016-03-03 jue>
- Dónde: Campus Madrid, Calle Manzanares, 1, Madrid
- Mapa: http://www.openstreetmap.org/way/7648766
- URL: http://www.meetup.com/es-ES/Node-js-Madrid/events/227675594/

En marzo os traemos una charla conjuntamente con nuestros amigos de h4ckademy: una empresa de Londres que viene a Madrid a contarnos cómo han tomado un sistema legacy con .NET y lo han migrado a Node.js con microservicios. Y para que podáis practicar, ¡será en inglés, por supuesto!

Carving Up Legacy with Microservices

The London-based company GuideSmiths is going to introduce us how they migrated a £90M per annum revenue jobs site from a legacy .Net platform to an AWS / Docker / Node.js based one in 9 months.

- Steve Cresswell
- Felipe Polo

** I Open Datathon ETSINF UPV sobre uso de datos abiertos
- Cuándo: <2016-03-04 vie>
- Dónde: UPV
- Mapa: 
- URL: http://s.coop/opendatathon
- Hahstag: #OpenDatathon

Los participantes tendrán tres semanas para crear un proyecto basado en datos abiertos, ya sea una visualización o una aplicación web. Los proyectos finalistas serán presentados el 4 de marzo en ETSINF UPV.

Se abre el plazo para presentar propuestas al primer OpenDatathon ETSINF –UPV organizado por MUGI, el Máster en Gestión de la Información de la ETSINF UPV-, l’Escola Tècnica Superior d’Enginyeria Informàtica de la UPV y el [[http://dataupv.webs.upv.es][Grupo DataUPV]] con el fin de promocionar, promover y divulgar el uso de datos abiertos, especialmente entre los miembros de la comunidad universitaria.

El plazo de presentación de proyectos estará abierto hasta el próximo 29 de febrero de 2016.

El I OpenDatathon cuenta con 3 categorías:

1. mejor historia sobre los datos
2. mejor herramienta de exploración de datos
3. mejor aplicación basada en predicción de datos.
4. También habrá una categoría especial "Premio Cátedra Ciudad de Valencia UPV" con retos que usen datos abiertos del portal del ayuntamiento de Valencia sobre rutas, salud o movilidad.

Todos los proyectos finalistas recibirán un diploma acreditativo. Adicionalmente por cada reto se prevé un primer premio de 350 euros y un segundo premio de 150 euros.

Una vez recibidas las propuestas se seleccionarán 5 finalistas por categoría que tendrán la oportunidad de exponer sus trabajos el 4 de marzo en la ETSINF, fecha próxima a la celebración mundial del Open Data Day.



** Día de los Datos Abiertos Madrid
- Cuándo: <2016-03-05 sáb 10:00-20:00>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: https://okfn-spain.github.io/madrid.opendataday.org

** Día de los Datos Abiertos Barcelona
- Cuándo: <2016-03-05 sáb>
- Dónde: 
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: https://okfn-spain.github.io/madrid.opendataday.org

apps4citizens organizará el Open Inspiration Data Day en la Fábrica Lehman (Barcelona), para promover el desarrollo de aplicaciones aprovechando el potencial de los datos abiertos. Será el 5 de marzo y contará con especialistas que buscarán estimular a los participantes.
** Día de los Datos Abiertos Bilbao
- Cuándo: <2016-03-05 sáb>
- Dónde: 
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: https://okfn-spain.github.io/madrid.opendataday.org

MORElab research group and Bilbao City Council will organize the local event at Auzo Factory Rekalde on March 4th. More info at [Open Data Day Bilbao http://opendataday.deusto.es].
** Día de los Datos Abiertos Girona
- Cuándo: <2016-03-05 sáb>
- Dónde: 
- Mapa:
- URL: 

Girona, Municipal City Archive of Girona will publish the dataset of the fonds that it keeps.
** Día de los Datos Abiertos Granada
- Cuándo: <2016-03-05 sáb>
- Dónde: 
- Mapa:
- URL: 

The Free Software Office in the University of Granada will organize its third Granada2016 Open Data and Projects Hackatón, place TBD, starting on March 4th and ending on Monday 7th in the morning. Please check the page for details. Several topics have been proposed: Analysis of election data in Spain and elsewhere. Gender in university degrees and students. Street naming analysis

** Reunión GNOME Hispano
- Cuándo: <2016-03-21 lun 18:30-20:45>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/gnome-hispano 

* Abril
** Festival Internacional de Periodismo de Perugia
- Cuándo: <2016-04-06 mié>--<2016-04-10 dom>
- Dónde: Perugia, Italia
- Mapa: 
- URL: http://www.festivaldelgiornalismo.com/

** 25th International World Wide Web Conference
<2016-04-11 lun>--<2016-04-15 vie>
http://www2016.ca/
** Akademy-es 2016
- Cuándo: <2016-04-15 vie>--<2016-04-17 dom>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: https://www.kde-espana.org/akademy-es2016/
he KDE® Community is an international technology team dedicated to creating a free and user-friendly computing experience, offering an advanced graphical desktop, a wide variety of applications for communication, work, education and entertainment and a platform to easily build new applications upon. We have a strong focus on finding innovative solutions to old and new problems, creating a vibrant atmosphere open for experimentation.site* Mayo
** Reunión GNOME Hispano
- Cuándo: <2016-04-18 lun 18:30-20:45>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/gnome-hispano



** Reunión GNOME Hispano
- Cuándo: <2016-04-18 lun>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/gnome-hispano

** Newsimpact Madrid
- Cuándo: <2016-04-25 lun 08:45-17:30>
- Dónde: Jardín Metropolitano, Hispainia & Oriental, Madrid
- URL: http://newsimpact.io
- Language: English + Spanish translation
- Moderation​: Rina Tsubaki & Mattia Peretti 

*** Schedule
- 08:45­09:30, Registration 
- 09:30­10:00, Opening Remarks
 - Wilfried Rütten, Director, European Journalism Centre 
 - Vicent Partal, Vice­Chairman, European Journalism Centre / Founder and 
Director of VilaWeb.cat
 - Google Spain 
- 10:00­11:00, Panel: Data­Driven Storytelling ­ New Approaches & Practices 
 - Mar Cabra, Head of the Data & Research Uni, ICIJ
 - Nikolas Kaiser­Bril, Co­founder, Journalism++
 - Daniele Grasso, El Confidencial Lab
 - Jacopo Ottaviani, Journalism Grants grantee and trainer 
 - Moderator: Raúl Rodríguez, Assistant Manager, 20M newspaper
- 11:00­11:15, Coffee Break 
- 11:15­12:00, Fireside Chat: Digital Newsroom ­ From Gathering News to Storytelling in the Digital Age 
 - Louise Roug, Global News Editor, Mashable
 - Nevine Mabro, Head of Foreign News, Channel 4 News
- 12:00­12:30, Keynote: Measuring Impact and Audience Behaviour with Data 
Kiki Von Glinow, Director of Growth and Analytics, The Huffington Post
- 12:30­13:30, Lunch
- 13:30-14:30
 - Session 1, Google Search, Trends & Maps [in Spanish] Millán I. Berzosa, Media Trainer, Google News Lab.
 - Session 2, How to attract and engage with new young audiences.
  - Gonzalo Pastor, Executive Director, VICE Spain
  - Lucia González, Verne
- 14:30 ­ 14:45 Room Change 
- 14:45-15:45
 - Session 3, ICIJ Session: ​Global exclusives through collaboration (Exclusivas globales a través de la colaboración, in Spanish).
 - Session 4, Tips & Tricks: VR & 360° storytelling at euronews. Thomas Seymat, Data Journalist/ Live­Blog Editor, euronews 
- 15:45­16:00,  Break/ Room change 
- 16:00­16:30, Expert Session: Digital Transformation and Innovation for BBC News Robert McKenzie, Editor, BBC News Labs (TBC)
- 16:30­17:30, Panel: ​New challenges: from online to mobile (in Spanish, with an English interpretation)  
 - Nacho Cardero, ElConfidencial
 - María Ramírez, Elespanol.com
 - Fernando Berlín, radiocable.com
 - Juan Luis Sanchez, eldiario.es
 - Moderator: Dani Seseña, Cámara Abierta TVE

** D-CENT and Open Knowledge Labs meetup
- Cuándo: <2016-04-26 mar>
- Dónde: Makers of Barcelona (MOB), Calle Bailén 11, bajos.
- URL: https://attending.io/events/d-cent-and-open-knowledge-labs-meetup
- Idioma: English
- Mapa: http://www.openstreetmap.org/way/4745499

** TICTeC 2016
- Cuándo: <2016-04-27 mié>--<2016-04-28 jue>
- Dónde: Edificio Este, World Trade Center, Barcelona 8039
- URL: https://www.mysociety.org/files/2015/09/Agenda-2016.pdf
- Language: English

** Domina Git y GitHub
30 sesiones del [[http://medialab-prado.es/article/periodismo_de_datos_-_grupo_de_trabajo][grupo de periodismo de datos de Medialab-Prado]] y cuarta de [[https://twitter.com/journocodersMAD][@JournocodersMAD]]. Si en estas 29 sesiones desde que comenzamos en 2011 no has aprendido [[https://git-scm.com/][Git]] y no has usado [[https://github.com][GitHub]], no sabes lo que te estás perdiendo.
- Cuándo: <2016-04-27 mié 18:30-20:45>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/domina-git-y-github
- Meetup: http://www.meetup.com/es-ES/Madrid-Periodismo-de-datos-Meetup/events/230516014/

** Rrrrevolucionem la primavera??? R per a Dummies i periodistes
Ja ha arribat la primavera i estem tots RRRRevolucionats, així que a Hacks/Hackers Barcelona hem preparat una nova sessió per sacsejar el periodisme. 
- Cuándo: <2016-04-29 vie>
- Dónde: Barcelona Activa
- Meetup: http://www.meetup.com/es-ES/Hacks-Hackers-Barcelona/events/230399129/?a=socialmedia
- Organiza: Hacks/Hackers Barcelona

* Mayo
** IV Jornadas Periodismo Datos #JPD16
- Cuándo: <2016-05-05 jue>--<2016-05-07 sáb>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://jpd16.okfn.es
- Entradas: http://jpdatos.eventbrite.es/?s=61065066

#+BEGIN_HTML
<div itemscope itemtype="http://schema.org/Event">
<a itemprop="url" href="http://periodismodatos.okfn.es"><div itemprop="name"><strong>Data Journalism Conference</strong></div>
</a>
<div itemprop="description">Spanish Data Journalism and Open Data Conference</div>
<div><meta itemprop="startDate" content="2016-05-05T12:00">Starts: 05/05/2016 12:00PM</div>
<meta itemprop="endDate" content="2016-05-08:00.000">Ends: 2016-05-08:00.000
</div>
<div itemprop="location" itemscope itemtype="http://schema.org/PostalAddress">
<div itemprop="streetAddress">Calle Alameda 15</div>
<div><span itemprop="addressLocality">Madrid</span>, <span itemprop="addressRegion">Madrid</span></div><div itemprop="postalCode">28014</div>
<div itemprop="addressCountry">Spain</div>
</div>
#+END_HTML

** News Impact Summit London
- Cuándo: <2016-05-12 jue>
- Dónde: Londres, Reino Unido
- URL: http://newsimpact.io
- Fuente: http://ejc.net/projects/news/article/ejc-announces-a-new-series-of-news-impact-summits-in-2016

** Reunión GNOME Hispano
- Cuándo: <2016-05-16 lun 18:30-20:45>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/gnome-hispano
** ESS Visualization Workshop
- Cuándo: <2016-05-17 mar>--<2016-05-18 mié>
- Dónde: Valencia
- Mapa: 
- URL: http://ec.europa.eu/eurostat/cros/content/2016-visualisation-workshop_en
- Organiza: Comisión Europea (Eurostat), con el apoyo de DevStat (España) www.devstat.com, en consorcio con el Centro Nacional para la Enseñanza de Estadística (Rumanía) y Prueba abierta (España).

El evento abordará la visualización como una herramienta para el análisis y visualización de datos y como instrumento de difusión.

El taller tiene como objetivo aumentar la conciencia sobre el tema de la visualización de las estadísticas; identificar las mejores prácticas emergentes para identificar sinergias y opciones para los esfuerzos de desarrollo conjuntos; compartir las mejores prácticas, nuevas ideas, herramientas y experiencias. Estos objetivos tienen que contribuir al objetivo más amplio de facilitar la cooperación dentro de la ESS en el desarrollo e implementación de soluciones metodológicas comunes, alineada con la cartera de ejecución de ESS Visión 2020 http://ec.europa.eu/eurostat/web/ess/about-us/ess-vision-2020 (en particular, los aspectos de visualización de la DIGICOM proyecte) 
http://ec.europa.eu/eurostat/documents/42577/6906243/DIGICOM+Business+Case+1.0/8a2f1b42-4101-4208-9c49-1d1819604047

** Democracy Lab. Common Technology and the Democratic City
- Cuándo: <2016-05-23 lun>--<2016-05-27 vie>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://dcentproject.eu/dcentmadrid/democracy-lab/
- Registro: http://dcentproject.eu/dcentmadrid/register
The week begins with a four-day Democracy Lab (23-27 May, Medialab-Prado) delivering workshops, hackathons and open sessions to develop, think and design tools, processes and strategies for democratic participation.
*** Creating a Democratic Commons Network

Hosted by: Xabier Barandiaran (Faculty of Social Work, University of the Basque Country; IAS Research Centre for Life, Mind and Society; and Wikitoki); Yago Bermejo Abati (LaboDemo).
*** Data Journalism with Decide Madrid

Hosted by: Pablo Aragon (Eurecat; Internet Interdisciplinary Institute, Open University of Catalonia); David Cabo (Fundació Civio) and Eva Belmonte (Fundació Civio).
*** Direct Democracy: Legal strategies for local implementation

Hosted by: Juan Carlos Madroñal (Más Democracia); Francisco Jurado (Andalucian Parliament); and Juan Moreno Yagüe (Andalucian Parliament).
*** Coding Democracy: Ruby on rails hackathon

Hosted by: Consul Team, Madrid City Council
*** Digital Democracy: D-CENT, citizen engagement and economic empowerment

Hosted by: D-CENT and Medialab-Prado

*** Initiatives for open democracy and a decentralised Internet

Hosted by: D-CENT; Redecentralise.org; and Labodemo.net
*** Workshop: Making Modern Direct Democracy Work

Hosted by: Bruno Kaufmann (Initiative and Referendum Institute Europe); and invited guests.
** Ciudades democráticas
Tecnologías de los comunes y derecho a la ciudad democrática
- Cuándo: <2016-05-23 lun>--<2016-05-28 sáb>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid. Museo Reina Sofía.
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://ciudades-democraticas.cc

La ciudad de Madrid será entre el 23 y 28 de mayo la capital mundial de la participación ciudadana y tecnológica. El D-Cent Project, el Ayuntamiento de Madrid y el Museo Nacional Centro de Arte Reina Sofía han programado una intensa semana llena de actividades sobre ciudades democráticas, tecnologías de los comunes y participación ciudadana. El programa del encuentro se divide en el Democracy Lab y en la Conferencia Internacional.

** Hackathon Fujitsu Open Data para Smart Cities
- Plazo: <2016-05-22 dom>
- Cuándo: <2016-05-24 mar>
- Dónde: Pabellón 8 de IFEMA, Calle de Ribera del Sena, Madrid.
- Mapa: http://www.openstreetmap.org/way/34050269
- URL: http://dcentproject.eu/dcentmadrid/conference/
Hackathon Fujitsu Open Data para Smart Cities patrocinado conjuntamente por Fujitsu España y Fujitsu Laboratories.

En Fujitsu queremos fomentar el desarrollo de nuevos métodos de exploración de datos, colaborando tanto en los avances científicos de ámbito público como en aquellos que afectan a la vida cotidiana de las personas. Creemos que Open Data en general y Linked Open Data en particular pueden desempeñar un papel vital en nuestras vidas, ayudando a la Transformación Digital de la Sociedad a través del uso de fuentes públicas de datos.

Por este motivo, en 2015 patrocinamos el primer concurso sobre Linked Open Data y este año lanzamos un Hackathon sobre el mismo tema. En Fujitsu queremos hacer realidad el Linked Open Data.

El Hackathon se desarrollará el día 24 de mayo dentro del evento Digital Enterprise Show, que tendrá lugar en el Pabellón 8 de IFEMA en Madrid. Fujitsu otorgará un premio en metálico de 3.000 euros al mejor desarrollo. Este premio será presentado públicamente durante el Fujitsu World Tour el día 25 de mayo también en el Pabellón 8 de IFEMA.


** I Congreso Iberoamericano Nebrija PIATCOM: tendencias, competencias y perfiles profesionales en el sector de la comunicación
- Call for Abstracts DEADLINE: <2016-03-13 dom>
- Cuándo: <2016-05-24 mar>--<2016-05-25 mié>
- Dónde: Universidad Nebrija. Facultad de Ciencias de la Comunicación. Campus de la Berzosa. Hoyo del Manzanares. Madrid
- Mapa: http://www.openstreetmap.org/relation/346078#map=17/40.59978/-3.94578
- URL: http://www.congresopiatcom.com/
** Jornadas SIG Libre
+ Call for Abstracts DEADLINE: <2016-03-13 dom>
+ Cuándo: <2016-05-24 mar>--<2016-05-29 dom>
+ Dónde: Aulas de Informática, Facultad de Letras (Universitat de Girona)
+ Mapa: 
+ URL: http://www.sigte.udg.edu/jornadassiglibre/jornadas-sig-libre/talleres/

Las Jornadas de SIG Libre son un evento de referencia en el sector de las tecnologías libres en el ámbito de la información geográfica. Son un punto de encuentro donde compartir conocimientos, experiencias y crear sinergias. El idioma de la conferencia es el Español.

 
La International QGIS User and Developer Conference quiere convertirse en el espacio de referencia, y un punto de encuentro para la familia de usuarios y desarrolladores que orbitan alrededor del proyecto QGIS, con el objetivo de recopilar experiencias y compartir el conocimiento sobre QGIS. El idioma de la conferencia es el Inglés.

** Common Technology and the Democratic City conference
- Cuándo: <2016-05-27 vie>--<2016-05-28 sáb>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://dcentproject.eu/dcentmadrid/conference/
The Common Technology and the Democratic City conference (27-28 May, Museo Reina Sofia) will conclude the week’s activities. Prompting discussion on network democracy, new forms of citizen participation and digital commons in democratic Cities, the conference will showcase the success of the European D-CENT project and look at the future of digital democracy.

The event will gather politicians, activists, researchers, social movements, hackers and Cities to explore innovative methods, digital tools, and policies to strengthen large-scale citizen participation in the political process at European and global level. Participants will debate public policies at the municipal, national and European level to transform democracy and promote transparency to devolve power to citizens and fight concentration of power within public institutions.

By sharing real-world insights from these global experiments and demonstrating the digital tools being used, the event will provide a positive vision of collective intelligence in 21st Century democracy.



** Call for Abstracts Open Data Research Symposium
   DEADLINE: <2016-05-30 lun>
http://odresearch.org/abstract.html

Conferencia el 5 de octubre

** News Impact Summit Doha
- Cuándo: <2016-05-30 lun>
- Dónde: Doha, Qatar
- URL: http://newsimpact.io
- Fuente: http://ejc.net/projects/news/article/ejc-announces-a-new-series-of-news-impact-summits-in-2016

* Junio
** Q2016 European Conference on Quality in Official Statistics
<2016-05-31 mar>--<2016-06-03 vie>
- URL: http://www.q2016.es/?lang=es
- Lugar: Círculo de Bellas Artes en Madrid, España
- Fechas: del 1 al 3 de Junio de 2016.

** Iniciación de Web Scraping con Python
- Cuándo: <2016-06-01 mié 18:30-20:30>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/iniciacion-a-web-scraping-con-python

El 1 de junio escrapearemos la web con Python, o como también se dice, webscraping con Python de la mano de Nicolás Pérez (@nicolasperezi), reportero de datos de El Español.

** CartoDBeers Elecciones 26J
- Cuándo: <2016-06-01 mié 19:30-20:30>
- Dónde: Palacio de la Prensa, Gran Vía 46, 2ª planta. 28013, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: https://www.eventbrite.es/e/entradas-cartodbeers-elecciones-26j-25258224028

Taller enfocado a la visualización de los datos electorales para las elecciones generales del 26 de Junio. Tras este workshop, tendremos el placer de invitaros a unas cervezas y así poder charlar sobre cómo sacar el mayor partido a vuestras visualizaciones a través de CartoDB.
** Open Expo 2016
- Cuándo: <2016-06-02 jue>
- Dónde: Ático de la Estación de Chamartín, Calle de Rodríguez Jaén, Madrid.
- Mapa: http://www.openstreetmap.org/relation/4804690
- URL: http://www.openexpo.es
- Entrada: Varía el precio, http://www.openexpo.es/openexpo-2016/inscripcion

OpenExpo 2016, III Feria y Congreso anual sobre FLOSS y Open World Economy (Open Data y Open Innovation) que reúne el 2 de junio 2016 en el Espacio MEEU, Ático de la Estación de Chamartín (Madrid) a más de 2.000 personalidades del sector, profesionales y empresas en búsqueda de generación de negocio.

• Encuentro con más de 2.000 profesionales senior del sector en solo un día: representantes de las principales empresas e instituciones, desarrolladores de código abierto, hackers, expertos, proveedores y usuarios de todos los niveles.
• Un día de conferencias, casos de éxito, Keynotes, talleres, mesas redondas, demos y otras actividades paralelas en torno al mundo de las tecnologías libres.
• Más de 100 empresas participantes que presentarán sus novedades y soluciones tecnológicas.

** Debate sobre datos abiertos
- Cuándo: <2016-06-02 jue 01:30-02:10pm>
- Dónde: Ático de la Estación de Chamartín, Calle de Rodríguez Jaén, Madrid.
- Mapa: http://www.openstreetmap.org/relation/4804690
- URL: http://www.openexpo.es
- Entrada: Varía el precio, http://www.openexpo.es/openexpo-2016/inscripcion

Mesa redonda moderada por Adolfo Antón Bravo, presidente de Open Knowledge España y coordinador del programa de Transparencia y Datos Abiertos de Medialab-Prado. Con la participación de:
- María Poveda, de ODI Madrid y OEG-UPM. Datos abiertos y enlazados (Linked Open Data)
- Alberto Abella, de Open Knowledge España, profesor en URJC. Datos abiertos e impacto en la sociedad. ¿Como argumentar que invertir en datos abiertos no es un mal uso de los recursos públicos? ¿Tenemos los datos de su impacto?¿Sabemos como se produce? ¿Hay alguna buena práctica o seguir? ¿Cuanto hay de postureo en las apuestas por la apertura de datos?. 
- representante del ayuntamiento de Madrid (por confirmar)

*** Ponentes
**** Adolfo Antón Bravo
Adolfo Antón Bravo ([[https://www.twitter.com/adolflow][@adolflow]]) es doctor en Ciencias de la Información por la Universidad Complutense de Madrid donde ha realizado su tesis sobre Tecnologías de la Web Semántica. Presidente de Open Knowledge España y editor de Infotics.es (@infotics), ha coordinado las actividades del grupo de trabajo de Periodismo de Datos de Medialab-Prado y las Jornadas de Periodismo de Datos (2014-2016). Ha trabajado o trabaja como diseñador, periodista, formador y es un apasionado del Software Libre y el conocimiento abierto. En la actualidad coordina el programa de Transparencia y Datos Abiertos de Medialab-Prado.


**** Alberto Abella
Alberto Abella es profesor asociado de la URJC y investigador y doctorando sobre el impacto económico de los datos abiertos. Fundador de OK Spain y miembro de su junta directiva. Ha desarrollado una una métrica (http://meloda.org) para  evaluar como optimizar la publicación de open data. Publicó de 2003 a 2007 el I, II y III libro blanco del software libre en España. Actualmente sus líneas de investigación se centran en determinar el impacto de la economía de los datos. En el ámbito privado también ha participado en proyectos europeos para el fomento de empreas basadas en datos y es evaluador para incubadoras de negocios de startups con modelos de negocio basados en datos.
**** María Poveda
María Poveda Villalón es doctora en Inteligencia Artificial y máster en Investigación por la Universidad Politécnica de Madrid (UPM). Actualmente es investigadora postdoctoral en el Ontology Engineering Group de la UPM, grupo que alberga el Nodo para la región de Madrid del Open Data Institute. Sus intereses en investigación son principalmente la ingeniería ontológica, la web semántica y datos enlazados. Durante los últimos años ha realizado estancias de investigación en centros extranjeros como University of Liverpool (2011), Free University of Berlin (2012) y en empresas como Mondeca en Paris (2013). Además ha participado en numerosos proyectos de investigación tanto a nivel nacional como internacional.

** R en Junio en Medialab-Prado
- Cuándo: <2016-06-09 jue 19:00-20:30>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://www.meetup.com/es-ES/Grupo-de-Usuarios-de-R-de-Madrid/events/231334596/

Daniel Santolaria: Daniel nos presentará una solución sobre openCPU como servidor web para aplicaciones de R. Y de un ejemplo propio que se llama "Modeler", y que se trata de un modelizador web de series temporales. Éste se puede ver en medible.es

Santiago Mota: Santiago hará una introducción a la plataforma Kaggle, qué es, cómo funciona y algunos consejos prácticos para los que están empezando.

** ICA Fukuoka 2016, conference of the International Communication Association
- Cuándo: <2016-06-09 jue>--<2016-06-13 lun>
- Dónde: Fukuoka, Japón
- Mapa: 
- URL: http://icahdq.org

** Evento transparente
- Cuándo: <2016-06-15 mié 10:00-18:00>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://eventotransparente.org/

*** Horario
- 10:00, Recepción y acreditaciones
- 10:15, Presentación
- 10:30, Panel 1: Participación ciudadana
- 11:45, Café
- 12:15, Panel 2: Datos abiertos
- 13:30, Panel 3: Cómo mejorar la Legislación de Transparencia
- 15:00, Cóctel
- 16:15, Panel 4: Gobierno abierto
- 17:45, Clausura: Luis Furnells, Presidente Ejecutivo Grupo Oesía


** GEN Summit
- Cuándo: <2016-06-15 mié>--<2016-06-17 vie>
- Dónde: Viena, Austria
- Mapa: 
- URL: http://www.gensummit2016.org/

How can the media industry deal with Facebook, Apple, Google, Amazon and other mega-platforms offering news to their users? This is the major question for 2016 and the sixth annual GEN Summit will explore the most relevant solutions for your newsroom. Over-the-top platforms claim to want to partner with media organisations and share revenue, but who will own the data and the readers’ loyalty? Content distribution is becoming a common battleground for legacy media and pure online players alike. For the first time, both are facing the same struggle. Join more than 600 Editors-in-Chief and media innovators for three days in Vienna, presented by the Global Editors Network, June 15-17, 2016.
** Data Journalism Awards
   DEADLINE: <2016-04-10 dom>
- Cuándo: <2016-06-17 vie>
- Dónde: Viena, Austria
- Mapa: 
- URL: http://www.globaleditorsnetwork.org/programmes/data-journalism-awards/

Estos son los únicos premios mundiales que reconocen y ayudan a visibilizar la labor periodística que combina la visualización y el análisis de datos para narrar historias innovadoras. Entre los ganadores de anteriores ediciones de se encuentran The New York Times, ProPublica, The Guardian o La Nación (de Argentina). La fecha límite para presentar los proyectos es el 10 de abril a media noche (horario del Meridiano de Greenwich) y la cuantía de los premios es €1.000. Los premios #DJA2016 están orientados a redacciones y periodistas de organizaciones y grupos editoriales de cualquier tamaño, tanto grandes como pequeños. Se reconocen a los mejores trabajos en 12 categorías, incluyendo:

- Mejor trabajo de visualización de datos 
- Mejor investigación 
- Mejor app de datos aplicada al periodismo 
- Mejor web de periodismo de datos 
- Mejor portfolio individual 
- Mejor uso de datos en una noticia de última hora 
- Premio a datos abiertos 
- Premio de excelencia (premio del jurado y premio del público) 

El concurso está organizado por Global Editors Network, una plataforma que cuenta con el apoyo de Google y Knight Foundation y que aglutina jefes de redacción e innovadores en medios de comunicación comprometidos con el periodismo de alta calidad.
** Taller de PostGIS y CartoCSS con CartoDB
- Cuándo: <2016-06-18 sáb 10:00-13:00>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/taller-de-postgis-y-cartocss-con-cartodb

Taller organizado por GeoInquietos Madrid será de dificultad intermedia ajustado para aquellos geoinquietos interesados en el análisis de bases de datos espaciales con PostGIS, así como el diseño de visualizaciones con el lenguaje de estilos CartoCSS, ambos dentro del editor de CartoDB. 

** Reunión GNOME Hispano
- Cuándo: <2016-06-20 lun 18:30-20:45>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/gnome-hispano
** Wikimania 2016
- Proposals:    DEADLINE: <2016-03-30 mié>
- Cuándo: <2016-06-22 mié>--<2016-06-28 mar>
- Dónde: Esino Lario, Lecco, Lombardía, Italia
- Mapa: 
- URL: https://wikimania2016.wikimedia.org/wiki/Main_Page

Wikimania is the annual conference celebrating Wikipedia and its sister free knowledge projects with conferences, discussions, meetups, training and a hackathon. Hundreds of volunteer editors come together to learn about and discuss projects, approaches and issues.

Join us in Esino Lario, Province of Lecco, Lombardy Region, Italy, on June 22–23 (pre-conference), 24–26 (main conference) and 27–28 (post-conference), 2016.

* Julio
** News Impact Summit Berlin
- Cuándo: <2016-07-01 vie>
- Dónde: Berlín, Alemania
- URL: http://newsimpact.io
- Fuente: http://ejc.net/projects/news/article/ejc-announces-a-new-series-of-news-impact-summits-in-2016
** 2nd Swiss Open Cultural Data Hackaton
- Cuándo: <2016-07-01 vie>--<2016-07-02 sáb>
- Dónde: Basel University Library / Digital Humanities Lab, Basilea, Suiza.
- URL: http://make.opendata.ch/wiki/event:2016-07

You can already bring in ideas about ways to use cultural data. Have a look at the Swiss cultural data and data from heritage institutions abroad published under open licenses:
- Swiss Data Sources
- Open Cultural Data (Worldwide)

You can help by sharing cultural data

You may own yourself cultural data that you are ready to share. Please look at these infosheets (German / French) on how to share data. If you have further questions, please feel free to contact beat.estermann@openglam.ch.

Share your discoveries of unspotted cultural data

Maybe you are aware of interesting cultural data. In preparation for the hackathon we are putting together a list of such datasets links to interesting data. We encourage you to contribute to it by adding new items.

Share Project Ideas

You can already bring in ideas about ways to use cultural data. Feel free to take part in an ongoing brainstorming on this page. 
** SIGIR 2016
<2016-07-17 dom>--<2016-07-21 jue>

39th International ACM SIGIR Conference on Research and Development in Information Retrieval, exactly 30 years since SIGIR 1986, also held in Pisa.

Researchers, academics, students, and industry leaders working in the broad area of information retrieval, are invited to join the conf for a rich, five-days program featuring full paper presentations, poster presentations, system demonstrations, tutorials, specialized workshops, an industry-oriented event, and social events.

The SIGIR conference is the major international forum for the presentation of new research results and for the demonstration of new systems and techniques in the field of information retrieval (IR). The General Chairs and Program Chairs of SIGIR 2016 invite all those working in areas related to IR to submit high-impact original papers for review. SIGIR 2016 welcomes contributions related to any aspect of IR theory, foundations, techniques, and applications, and solicits proposals for workshops, demonstrations, tutorials, and industry-oriented papers.

http://sigir.org/sigir2016/

** Reunión GNOME Hispano
- Cuándo: <2016-07-18 lun 18:30-20:45>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/gnome-hispano

** SRCCON
- Cuándo: <2016-07-28 jue>--<2016-07-29 vie>
- Dónde:  Pacific Northwest College of Art, Portland, Oregon, EE.UU.
- Mapa:
- URL: http://srccon.org/

SRCCON is a hands-on conference focused on the practical challenges news technology and data teams encounter every day. Active participation is at the center of SRCCON, and we work to make it an inclusive and welcoming event where people can feel comfortable jumping in to work on complex problems. We welcome participants from all fields—if you want to strengthen journalism online, we want you there.

* Octubre
** VII Congreso Internacional en Gobierno, Administración y Políticas Públicas
- Cuándo: <2016-10-03 lun>--<2016-10-05 mié>
- Dónde: 
- Mapa: 
- URL: http://www.gigapp.org/index.php/congreso/congreso-2016

“Construyendo una nueva cultura administrativa: políticas y gestión pública con la ciudadanía”
El Congreso Internacional en Gobierno, Administración y Políticas Públicas, organizado por el GIGAPP desde 2010, ha logrado constituirse en un Congreso anual de referencia en los temas de Gobierno, Administración y Políticas Públicas en Iberoamérica. La progresión del evento da cuenta del avance en cantidad y calidad del evento. Este evento es un espacio abierto pensado para presentar y debatir nuevas ideas y enfoques, experiencias e investigaciones de calidad y cultivar vínculos de colaboración y generación de redes de trabajo sobre los ejes temáticos en los que se enmarca.

** Open Data Research Symposium 2016
- Cuándo: <2016-10-05 mié 10:00-20:00>
- Dónde: Madrid, Spain
- Mapa: 
- URL: http://odresearch.org/ 
- Hashtag: [[https://twitter.com/hashtag/ODRS16?src%3Dhash][ODR16]]
** IODC 2016
<2016-10-06 jue>--<2016-10-07 vie>
4ª Conferencia Internacional sobre Datos Abiertos
Objertivos globales, impacto local
#+BEGIN_HTML
<div itemscope itemtype="http://schema.org/Event">
<a itemprop="url" href="http://opendatacon.org/"><div itemprop="name"><strong>International Open Data Conference</strong></div>
</a>
<div itemprop="description">Global goals, local impact. #iodc16</div>
<div><meta itemprop="startDate" content="2016-10-06T12:00">Starts: 10/06/2016 12:00PM</div>
<meta itemprop="endDate" content="2016-10-07:00.000">Ends: 2016-10-07:00.000
</div>
<div itemprop="location" itemscope itemtype="http://schema.org/PostalAddress">
<div><span itemprop="addressLocality">Madrid</span>, <span itemprop="addressRegion">Madrid</span></div><div itemprop="addressCountry">Spain</div>
</div>
#+END_HTML
http://opendatacon.org/

** Big Data Week
#+BEGIN_HTML
<div itemscope itemtype="http://schema.org/Event">
<a itemprop="url" href="http://london.bigdataweek.com/"><div itemprop="name"><strong>Big Data Week</strong></div>
</a>
<div itemprop="description">A global festival of Data</div>
<div><meta itemprop="startDate" content="2016-10-27T10:00">Starts: 27/10/2016 10:00AM</div>
<meta itemprop="endDate" content="2016-10-27:12.000">Ends: 2016-10-27:00.000
</div>
<div itemprop="location" itemscope itemtype="http://schema.org/PostalAddress">
<div><span itemprop="addressLocality">Londres</span>, <span itemprop="addressRegion">Londres</span></div><div itemprop="addressCountry">Reino Unido</div>
</div>
#+END_HTML
- Cuándo: <2016-10-27 jue>
- Dónde: etc.venues 155 Bishopsgate, Londres, Reino Unido
- Mapa: 51.5186567,-0.08028590000003533
- URL: http://london.bigdataweek.com/

Big data players from finance, healthcare & insurance, retail, IoT, entertainment, and travel are coming together for one week full of events.
Learn from industry leaders, attend meet-ups, webinars, workshops and discuss the latest developments in the big data world.

* Todo el año
* Becas, ofertas de trabajo
** Desarrollador web Python en Viderum
- URL: http://www.viderum.com/blog/2015/12/07/senior-python-web-developer
- Entidad: Viderum
- Publicado: <2015-12-15 mar>

Working in the fast-growing area of open data, we build open source tools to drive transparency, accountability and re-use. Based on CKAN, we‘ve built the the official national data portals from the UK to Brazil, US to Australia and many others.

We’re looking for someone passionate about the technical challenges of building software that is used as the infrastructure for open data around the world, so come join our growing team to shape the future of the open data ecosystem!

Key Skills

- Python, JavaScript, HTML, CSS
- Python web frameworks (we use Pylons and Flask)
- PostgreSQL and SQLAlchemy
- Self motivated, self-starter, able to manage your own time

Extra bonus points for:

- Open source projects/contributions
- Front end skills, particularly in data-vis
- You’ve written an app using open data before
- Experience working in a distributed team
- Ability to communicate in German

How to apply

Email jobs@viderum.com, with the subject line “Python Developer: CKAN”. Please include your CV and a link to your GitHub (or similar) profile.
** Becas El País y Amazon para festival internacional de Periodismo de Perugia
- Cuándo: <2016-02-16 mar>--<2016-03-04 vie>
- Fecha límite:   DEADLINE: <2016-03-04 vie>
- URL: http://politica.elpais.com/politica/2016/02/15/actualidad/1455539561_487834.html

Los participantes deben escribir un ensayo sobre el periodismo en la era digital
Los premiados ganarán un viaje al Festival Internacional de Periodismo de Perugia

** Premios de periodismo
http://gijn.org/2015/06/08/premios-para-periodistas-de-investigacion/

** eldiario.es
- URL: http://www.eldiario.es/redaccion/Quieres-tecnologico-revolucionara-sostenibilidad-medios_6_505059505.html
- desarrolladores para encargarse del diseño e implantación de la tecnología del modelo editorial y de socios de eldiario.es
- [[https://docs.google.com/document/d/1WeBBl6FqBbEAYDCJVk5um2R2vDsDxSjOaCuq_tiTT1s/edit][Lead Developer]] 
- desarrolladores front
- desarrolladores back-end.
** Contentmine Fellowship
- DEADLINE: <2016-06-03 vie>
- URL: https://discuss.okfn.org/t/announcing-contentmine-fellowships-applications-due-3-june-2016/2761
- Más info: https://contentmining.wordpress.com/2016/04/27/announcing-contentmine-fellowships/
- We welcome and encourage applicants from outside academia.
- Fellows will receive a £1000 grant and support for their project from the ContentMine team
- If you have any questions about the Fellowships, please contact graham [at] contentmine [dot] org

We require applicants to have basic knowledge of:

- UNIX command line
- At least one programming language such as javascript, java, python, R, MATLAB or other data science/statistical programming languages.
- Version control using git and github

** Reuters Institute hosts Google Digital News Journalist Fellowship
-   DEADLINE: <2016-06-17 vie>
- Pueden aplicar periodistas de Austria, Belgium, Czech Republic, Denmark, Finland, France, Germany, Greece, Hungary, Italy, Ireland, Netherlands, Norway, Poland, Portugal, Spain, Sweden, Switzerland and Turkey
- 5 años de inglés profesional
- URL: https://ijnet.org/en/opportunities/reuters-institute-hosts-google-digital-news-journalist-fellowship-europe
- Más info: http://reutersinstitute.politics.ox.ac.uk/news/call-applications-new-google-digital-news-journalist-fellowship-0
- Twitter: [[https://twitter.com/risj_oxford][@risj_oxford]]
The Reuters Institute for the Study of Journalism at Oxford University is seeking applications for its Google Digital News Journalist Fellowship in Oxford, United Kingdom.

The fellowship is intended for two six-month terms starting either October 2016 or January 2017. Fellows will work on a research paper based on some aspect of either the survey data for the 2017 Reuters Institute Digital News Report or digital journalism more generally with a direct focus on the professional and industry implications based on their own experience. 

* Cursos

* ProPublica's Summer Data Institute
  DEADLINE: <2016-03-31 jue>
First-ever Summer Data Institute, a 10-day intensive workshop on how to use data, design and code for journalism. The workshop will be from June 1st to 15th in our NYC offices. The deadline to apply is March 31st.

https://projects.propublica.org/graphics/summer
https://www.propublica.org/nerds/item/propublica-summer-data-institute

* Enlaces de interés

** Naked Data, Code for South Africa Newsletter
http://code4sa.org/newsletter/

* Ideas

** Calendario en Google
** Calendario en ICS
** Tinyletter
** Schema.org
** Orgmode


