#+BLOG: infotics
#+CATEGORY: calendario, evento, periodismodatos, datajournalism 
#+TAGS: boletín, periodismodatos, tinyletter, 
#+DESCRIPTION: Calendario de eventos relacionados con el conocimiento abierto para 2016
#+TITLE: Agenda de Open Knowledge España 2016
#+OPTIONS:  num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
Bienvenidxs a la agenda de eventos relacionados o de interés para la comunidad del conocimiento abierto España.

Si tienes un evento que proponer, añade [[https://github.com/OKFN-Spain/agenda/issues/new][una nueva issue]].

* Enero
** Madrid Python: Aplicaciones avanzadas de /Scraping/
- Cuándo: <2016-01-13 mié>
- URL: http://www.meetup.com/es-ES/Madrid-Python-Meetup/events/227936864/
** Grupo R de Madrid
- Cuándo: <2016-01-14 jue 19:00-20:45>
- Dónde: Medialab Prado, Plaza de las Letras, C/ de la Alameda, 15 , Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://www.meetup.com/es-ES/Grupo-de-Usuarios-de-R-de-Madrid/events/227983479/

*** Introducción a las Redes Neuronales
Francisco Rodríguez hará una introducción a las redes neuronales con R. Las redes neuronales vuelven a ser un campo de intensa actividad de investigación con la aparición de las nuevas topologías de red utilizadas en "Deep Learning".
*** Calidad del aire de Madrid
Carlos Ortega, a partir de los datos del propio Ayuntamiento de Madrid, mostrará un conjunto de análisis sobre cómo de saludable es el aire que respiramos.
*** Price Sensitivity Meter (PSM) in R
Karel Rodriguez mostrará cómo R se puede aplicar para crear una aplicación de uso empresarial que permite determinar el precio óptimo de compra utilizando percepciones psicológicas.

** MadridJS: Taller de programación funcional
- Cuándo: <2016-01-16 sáb 10:00-14:00>
- Dónde: Campus Madrid, Calle Manzanares, 1, Madrid.
- Mapa: http://www.openstreetmap.org/way/7648766
- URL: http://www.meetup.com/es-ES/madridjs/events/227302060/

De la mano de Javier Vélez, profesor de la UNED y co-organizador de MadridJS, aprenderemos a usar técnicas funcionales con JavaScript.

En este taller nos centraremos en abordar los elementos esenciales de la programación funcional tratando de describir como es la algoritmia funcional de una manera comparada en relación a la imperativa. Revisaremos los principios de diseño fundamentales, la ausencia de estado, la transparencia referencial, la inmutabilidad, etc. Estudiaremos recursividad y diseño funcional por inmersión, orden superior y compositividad, evaluación parcial y currificación, abstracciones de datos funcionales, streams y apis fluidas y lo que el tiempo nos permita... Todo ello nos proporcionará las skills necesarias para entender qué es exactamente una solución funcional, que la distingue de otras aproximaciones y nos preparará sin duda para hacer frente al emergente reto de las arquitecturas reactivas que se imponen como una realidad actual. 

** X Machine Learning Spain
- Cuándo: <2016-01-18 lun 18:30-20:30>
- Dónde: Campus Madrid, Calle Manzanares, 1, Madrid
- Mapa: http://www.openstreetmap.org/way/7648766
- URL: http://www.meetup.com/es-ES/MachineLearningSpain/events/227206352/

*** Pragmatic ML

How can you ensure that your work and use of ML gets the most impact in the domain you apply it to? From collaborating with all stake-holders to simulating how predictions will really be used, evaluating them domain-side and deploying models at scale in production, I’ll share some of the lessons I’ve learnt when it comes to integrate ML in real-world applications. Also, I’ll review some research problems and new open source software aimed at making it easier to create, experiment with, and operationalise predictive models.

Louis Dorard I'm the author of Bootstrapping Machine Learning, the first guide to Predictive APIs, and a co-founder of PAPIs.io­, the world's first conference on Predictive APIs and Predictive Apps. My goal is to help people use new machine learning technologies to make their apps and businesses smarter. I do this by writing, speaking and teaching.

*** Sistemas Cognitivos Artificiales: cuando aprender no es suficiente

Las técnicas de aprendizaje automático a menudo tratan de imitar la capacidad que poseen muchos organismos biológicos para adaptarse y progresar en su ecosistema, ¿pero es el aprendizaje la única clave de su adaptación? ¿Qué más capacidades cognitivas requieren los organismos para competir en entornos complejos y desestructurados? En esta charla adoptaremos un enfoque amplio de la cognición desde el punto de vista de la neuropsicología cognitiva, poniendo foco en nuevas aplicaciones empresariales y las tecnologías que las pueden hacer posibles.

Raúl Arrabales es ingeniero en informática, doctor en Inteligencia Artificial y MBA. En los últimos años ha liderado proyectos y startups de base tecnológica asumiendo diferentes roles, desde Jefe de Proyecto a CEO, en compañías como IBM, ARRIS, T-Online, Comaware y Altran. En el ámbito científico, contribuye al avance de las Ciencias Cognitivas con nuevos modelos computacionales.
También imparte clases y conferencias de Informática, Inteligencia Artificial, Inteligencia de Negocio, Robótica y Sistemas Cognitivos en diferentes centros, habiendo sido Profesor Doctor de la Universidad Carlos III de Madrid, Director del área de ingeniería en U-tad (Universidad Camilo José Cela) y director académico de MBiT School. Actualmente Raúl es Analytics Senior Manager en Accenture Digital. 


** Journocoders Madrid meets BBC API
- Cuándo: <2016-01-19 mar 18:45-20:30>
- Dónde: Medialab Prado, Plaza de las Letras, C/ de la Alameda, 15 , Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://s.coop/apibbc

Primero haremos un show&tell con los enlaces recomendados de #periodismodatos. Luego seguimos un tutorial muy básico sobre cómo trabajar con API. Para ello, utilizaremos la herramienta desarrollada por BBC News Labs: News Juicer API. Esta API permite acceder a los artículos en diferentes idiomas de más de 400 medios en todo el mundo. 

** Java vs Node.js: el encuentro
- Cuándo: <2016-01-19 mar>
- Dónde: Campus Madrid, Calle Manzanares, 1, Madrid
- Mapa: http://www.openstreetmap.org/way/7648766
- URL: http://www.meetup.com/es-ES/Node-js-Madrid/events/226495441/

Vamos a hacer una mesa redonda entre dos comunidades muy distintas en apariencia pero no tanto en la práctica: Java y Node.js. Moderada por el gran David Bonilla (@david_bonilla),  CEO de Otogami, y con los siguientes ponentes de lujo asiático:

- Javier Vélez (@javiervelezreye)
- Javier Abadía @javierabadia
- Pedro Palao
- Micael Gallego: @micael_gallego https://about.me/micael.gallego
- Leo Antoli (@lantoli) http://nextail.co
- Nacho Coloma (@nachocoloma) 

¿Qué podemos aprender unos de otros? ¿En qué nos parecemos y en qué nos diferenciamos? Entre otras cosas, hablaremos de:

- Tipado fuerte vs tipado débil.
- Productividad.
- Rendimiento: bruto y de entrada/salida.
- Soporte enterprise.
- Y los que salgan.

¿Te vas a perder el evento de moda en el nuevo año? 
** /D3.js Madrid/: introducción a /D3.js/ y creación de /dashboard/ con /DC.js/
- Cuándo: <2016-01-27 mié 19:30-20:30>
- Dónde: Oficinas de ShuttleCloud, Ronda de Atocha, 37 Oficina Derecha 28012, Madrid
- Mapa: http://www.openstreetmap.org/node/3423331185
- URL: http://www.meetup.com/es-ES/Madrid-D3-js/events/228011001

Segundo Meetup de [[http://www.meetup.com/es-ES/Madrid-D3-js/][D3.js Madrid]] con un par de charlas:

- Introducción a [[http://d3js.org][D3.js]] por [[https://twitter.com/maritrinez][Beatriz Martínez]]
- Crear un dashboard con [[https://dc-js.github.io/dc.js/][DC.js]], por [[https://twitter.com/ferblape][Fernando Blat]]

Se trata de dos charlas de 30 minutos de duración. Para la primera no hace falta ningún conocimiento previo de D3, mientras que para la segunda se darán por sabidos algunos conceptos. La idea es poder llegar tanto a gente que no conoce la librería como a gente que ya se ha peleado con ella y quiere profundizar en algún tema.

Así que animaros aunque no hayáis utilizado D3 nunca.

PD: por cierto, si te animas a dar una charla en futuras ediciones no dudes en decírnoslo. Queremos mantener el formato de dos charlas cortas, una introductoria y otra algo más avanzada.

* Febrero
** II Aniversario Data Science Spain
- Cuándo: <2016-02-04 jue>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://www.meetup.com/es-ES/Data-Science-Spain/events/227690627/

El próximo 4 de febrero DATA SCIENCE SPAIN cumple 2 AÑOS y queremos celebrarlo realizando el primer encuentro de 2016 con todos vosotros!!

Abrimos como siempre un call4papers para que podáis presentar vuestras ideas de charlas mandando un mail a cmartinez@synergicpartners.com
** Grupo R de Madrid
- Cuándo: <2016-02-11 jue 19:00-20:45>
- Dónde: Medialab Prado, Plaza de las Letras, C/ de la Alameda, 15 , Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://www.meetup.com/es-ES/Grupo-de-Usuarios-de-R-de-Madrid/events/228578129/

*** Programa:
- Gabriel Antonio Valverde Castilla: Introducción al "Deep Learning"
- Carlos J. Gil Bellosta: Modelos Estadísticos usando "rstan", interfaz R a Stan, el lenguaje que permite la creación y determinación de modelos estadísticos.
- Manuel García: "Artificial Bee Colony (ABC) Optimization" (paquete "ABCoptim"), optimización de funciones basado en agentes que simulan el comportamiento de una colonia de abejas.

** El periodista como analista de datos masivos
- Cuándo: <2016-02-17 mié 18:30-20:30>
- Dónde: Medialab Prado, Plaza de las Letras, C/ de la Alameda, 15 , Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://www.meetup.com/es-ES/Madrid-Periodismo-de-datos-Meetup/events/228690087/ y http://medialab-prado.es/article/analisis-de-datos-masivos-con-talend-open-studio
- Organizado por: Grupo de #periodismodatos de Medialab-Prado, /Journocoders Madrid/

El 17 de febrero alcanzamos las 28 sesiones y celebramos el día del amor por el software libre (#ILOVEFS) con un reto que afrontaremos entre todxs: la herramienta libre Talend Open Studio de la mano de Rigo, analista de datos del ICIJ, Consorcio Internacional de Periodistas de Investigación y que está acostumbrado a trabajar con grandes volúmenes de datos en proyectos periodísticos de primerísima fila como /Offshore Leaks/.

Imaginaos un programa que es capaz de cargar distintas archivos de datos de distintas fuentes, de realizar transformaciones a los datos como lo haríais con Refine, de mezclar esos datos e insertarlos en una base de datos y mostrara el resultado final con un informe del proceso. Ese es un ejemplo de lo que se puede hacer con Talend Open Studio y las herramientas ETL. 

** ALLDATA 2016: Second International Conference on Big Data, Small Data, Linked Data and Open Data
- Cuándo: <2016-02-21 dom>--<2016-02-25 jue>
- Dónde: Lisboa, Portugal
- URL: http://www.iaria.org/conferences2016/ALLDATA16.html

* Marzo
** Presentación informe España en Gobierno Abierto, 2013-2014
- Cuándo: <2016-03-01 mar 19:00-20:30>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/presentacion-informe-de-espana-en-gobierno-abierto-2013-2014
- Streaming: http://medialab-prado.es/article/streaming

España forma parte de la Alianza para el Gobierno Abierto desde 2011, iniciativa que integra a casi 70 países del mundo y cuyo propósito es compartir experiencias y desarrollar un foro permanente para avanzar hacia una mayor transparencia pública, combatir la corrupción con apertura de datos, incentivar la participación ciudadana y fortalecer los sistemas de control social y rendición pública de cuentas a través de las nuevas tecnologías.

El informe se realiza bajo una metodología común para todos los países participantes y recoge los hallazgos principales del avance de España en Gobierno Abierto. La información gubernamental se contrasta con las valoraciones y hallazgos de OSC implicadas con la transparencia y el gobierno abierto en España, ofrece argumentos críticos a la vez que propuestas constructivas, y detalla el avance y los retos de desarrollo de los 10 compromisos incluidos en el segundo plan de acción, siendo el compromiso más importante el lanzamiento del Portal de la Transparencia de la Administración General del Estado.

Este informe ha sido realizado por el Investigador del [[http://www.gigapp.org][GIGAPP]] (Grupo de Investigación en Gobierno, Administración y Políticas Públicas), Dr. César Nicandro Cruz-Rubio ([[https://twitter.com/cesarncruz][@cesarncruz]]). 

*** Invitados especiales:

- Dña. Victoria Anderica. Experta en transparencia y gobierno abierto. Responsable del área de Transparencia. Ayuntamiento de Madrid
- Dña. Victoria Figueroa. Directora de la Oficina de Transparencia y Acceso a la Información. Ministerio de la Presidencia 

** Circumvention Tech Festival
- Cuándo: <2016-03-01 mar>--<2016-03-06 dom>
- Dónde: Las Naves, Carrer de Joan Verdeguer 16, Valencia, España
- Mapa: http://www.openstreetmap.org/way/158789093#map=19/39.45850/-0.33798
- URL: http://www.circumventionfestival.es/

Se han registrado profesionales de 47 países diferentes y contamos con la participación de organizaciones como Tor, Electronic Frontier Foundation, Freedom of the Press Foundation, Xnet, Tactical Tech, Global Voices, Filtra.la, APC, Mozilla Foundation y muchas más.

** Carving Up Legacy with Microservices
- Cuándo: <2016-03-03 jue>
- Dónde: Campus Madrid, Calle Manzanares, 1, Madrid
- Mapa: http://www.openstreetmap.org/way/7648766
- URL: http://www.meetup.com/es-ES/Node-js-Madrid/events/227675594/

En marzo os traemos una charla conjuntamente con nuestros amigos de h4ckademy: una empresa de Londres que viene a Madrid a contarnos cómo han tomado un sistema legacy con .NET y lo han migrado a Node.js con microservicios. Y para que podáis practicar, ¡será en inglés, por supuesto!

Carving Up Legacy with Microservices

The London-based company GuideSmiths is going to introduce us how they migrated a £90M per annum revenue jobs site from a legacy .Net platform to an AWS / Docker / Node.js based one in 9 months.

- Steve Cresswell
- Felipe Polo

** I Open Datathon ETSINF UPV sobre uso de datos abiertos
- Cuándo: <2016-03-04 vie>
- Dónde: UPV
- Mapa: 
- URL: http://s.coop/opendatathon
- Hahstag: #OpenDatathon

Los participantes tendrán tres semanas para crear un proyecto basado en datos abiertos, ya sea una visualización o una aplicación web. Los proyectos finalistas serán presentados el 4 de marzo en ETSINF UPV.

Se abre el plazo para presentar propuestas al primer OpenDatathon ETSINF –UPV organizado por MUGI, el Máster en Gestión de la Información de la ETSINF UPV-, l’Escola Tècnica Superior d’Enginyeria Informàtica de la UPV y el [[http://dataupv.webs.upv.es][Grupo DataUPV]] con el fin de promocionar, promover y divulgar el uso de datos abiertos, especialmente entre los miembros de la comunidad universitaria.

El plazo de presentación de proyectos estará abierto hasta el próximo 29 de febrero de 2016.

El I OpenDatathon cuenta con 3 categorías:

1. mejor historia sobre los datos
2. mejor herramienta de exploración de datos
3. mejor aplicación basada en predicción de datos.
4. También habrá una categoría especial "Premio Cátedra Ciudad de Valencia UPV" con retos que usen datos abiertos del portal del ayuntamiento de Valencia sobre rutas, salud o movilidad.

Todos los proyectos finalistas recibirán un diploma acreditativo. Adicionalmente por cada reto se prevé un primer premio de 350 euros y un segundo premio de 150 euros.

Una vez recibidas las propuestas se seleccionarán 5 finalistas por categoría que tendrán la oportunidad de exponer sus trabajos el 4 de marzo en la ETSINF, fecha próxima a la celebración mundial del Open Data Day.



** Día de los Datos Abiertos Madrid
- Cuándo: <2016-03-05 sáb 10:00-20:00>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: https://okfn-spain.github.io/madrid.opendataday.org

** Día de los Datos Abiertos Barcelona
- Cuándo: <2016-03-05 sáb>
- Dónde: 
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: https://okfn-spain.github.io/madrid.opendataday.org

apps4citizens organizará el Open Inspiration Data Day en la Fábrica Lehman (Barcelona), para promover el desarrollo de aplicaciones aprovechando el potencial de los datos abiertos. Será el 5 de marzo y contará con especialistas que buscarán estimular a los participantes.
** Día de los Datos Abiertos Bilbao
- Cuándo: <2016-03-05 sáb>
- Dónde: 
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: https://okfn-spain.github.io/madrid.opendataday.org

MORElab research group and Bilbao City Council will organize the local event at Auzo Factory Rekalde on March 4th. More info at [Open Data Day Bilbao http://opendataday.deusto.es].
** Día de los Datos Abiertos Girona
- Cuándo: <2016-03-05 sáb>
- Dónde: 
- Mapa:
- URL: 

Girona, Municipal City Archive of Girona will publish the dataset of the fonds that it keeps.
** Día de los Datos Abiertos Granada
- Cuándo: <2016-03-05 sáb>
- Dónde: 
- Mapa:
- URL: 

The Free Software Office in the University of Granada will organize its third Granada2016 Open Data and Projects Hackatón, place TBD, starting on March 4th and ending on Monday 7th in the morning. Please check the page for details. Several topics have been proposed: Analysis of election data in Spain and elsewhere. Gender in university degrees and students. Street naming analysis

** Reunión GNOME Hispano
- Cuándo: <2016-03-21 lun 18:30-20:45>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/gnome-hispano 

* Abril
** Festival Internacional de Periodismo de Perugia
- Cuándo: <2016-04-06 mié>--<2016-04-10 dom>
- Dónde: Perugia, Italia
- Mapa: 
- URL: http://www.festivaldelgiornalismo.com/

** 25th International World Wide Web Conference
<2016-04-11 lun>--<2016-04-15 vie>
http://www2016.ca/
** Akademy-es 2016
- Cuándo: <2016-04-15 vie>--<2016-04-17 dom>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: https://www.kde-espana.org/akademy-es2016/
he KDE® Community is an international technology team dedicated to creating a free and user-friendly computing experience, offering an advanced graphical desktop, a wide variety of applications for communication, work, education and entertainment and a platform to easily build new applications upon. We have a strong focus on finding innovative solutions to old and new problems, creating a vibrant atmosphere open for experimentation.site* Mayo
** Reunión GNOME Hispano
- Cuándo: <2016-04-18 lun 18:30-20:45>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/gnome-hispano

** Q2016 European Conference on Quality in Official Statistics
<2016-05-31 mar>--<2016-06-03 vie>
Madrid, 31 mayo-3 junio
El Instituto Nacional de Estadística de España y Eurostat tienen el placer de invitarle a la Conferencia Europea sobre Calidad en las Estadísticas Oficiales (Q2016) que tendrá lugar en el Círculo de Bellas Artes en Madrid, España, del 1 al 3 de Junio de 2016.

El programa de la Conferencia se complementa además con una serie de cursos especializados, que se impartirán el día previo a la Conferencia (31 de Mayo de 2016).

Desde su creación en 2001, estas Conferencias han supuesto un marco idóneo para presentar y discutir el progreso y desarrollo de la calidad en las estadísticas oficiales, así como para el intercambio de metodologías y buenas prácticas entre expertos de diferentes ámbitos estadísticos (oficinas de estadísticas, organizaciones internacionales, investigadores y académicos).

La Conferencia pretende abarcar temas relevantes e innovadores en calidad, que van desde los desafíos y nuevos paradigmas en una sociedad impulsada por la información y el conocimiento, incluyendo el manejo de “Big data” y “estadísticas multi-fuente”, hasta los aspectos de gobernabilidad y gestión vinculados a la Visión 2020 o las lecciones aprendidas en las revisiones por pares (Peer review) 2013-2015 en el Sistema Estadístico Europeo. Además, siendo un foro abierto al debate, representa una oportunidad para presentar innovaciones en la medición y gestión de la calidad en campos y productos estadísticos específicos.

El sitio web de la Conferencia ofrece información sobre la sede de la conferencia, alojamiento, cursos de formación y eventos sociales, así como los plazos para la presentación de trabajos. Las inscripciones ya están abiertas.

Por favor si tienen alguna duda, contáctenos

¡Les esperamos en Madrid!

Gregorio Izquierdo                       Walter Radermacher
Presidente. INE España                Director General Eurostat. Chief Statistician of the European Union

http://www.q2016.es/?lang=es
** Reunión GNOME Hispano
- Cuándo: <2016-04-18 lun>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/gnome-hispano

** Newsimpact Madrid
- Cuándo: <2016-04-25 lun 08:45-17:30>
- Dónde: Jardín Metropolitano, Hispainia & Oriental, Madrid
- URL: http://newsimpact.io
- Language: English + Spanish translation
- Moderation​: Rina Tsubaki & Mattia Peretti 

*** Schedule
- 08:45­09:30, Registration 
- 09:30­10:00, Opening Remarks
 - Wilfried Rütten, Director, European Journalism Centre 
 - Vicent Partal, Vice­Chairman, European Journalism Centre / Founder and 
Director of VilaWeb.cat
 - Google Spain 
- 10:00­11:00, Panel: Data­Driven Storytelling ­ New Approaches & Practices 
 - Mar Cabra, Head of the Data & Research Uni, ICIJ
 - Nikolas Kaiser­Bril, Co­founder, Journalism++
 - Daniele Grasso, El Confidencial Lab
 - Jacopo Ottaviani, Journalism Grants grantee and trainer 
 - Moderator: Raúl Rodríguez, Assistant Manager, 20M newspaper
- 11:00­11:15, Coffee Break 
- 11:15­12:00, Fireside Chat: Digital Newsroom ­ From Gathering News to Storytelling in the Digital Age 
 - Louise Roug, Global News Editor, Mashable
 - Nevine Mabro, Head of Foreign News, Channel 4 News
- 12:00­12:30, Keynote: Measuring Impact and Audience Behaviour with Data 
Kiki Von Glinow, Director of Growth and Analytics, The Huffington Post
- 12:30­13:30, Lunch
- 13:30-14:30
 - Session 1, Google Search, Trends & Maps [in Spanish] Millán I. Berzosa, Media Trainer, Google News Lab.
 - Session 2, How to attract and engage with new young audiences.
  - Gonzalo Pastor, Executive Director, VICE Spain
  - Lucia González, Verne
- 14:30 ­ 14:45 Room Change 
- 14:45-15:45
 - Session 3, ICIJ Session: ​Global exclusives through collaboration (Exclusivas globales a través de la colaboración, in Spanish).
 - Session 4, Tips & Tricks: VR & 360° storytelling at euronews. Thomas Seymat, Data Journalist/ Live­Blog Editor, euronews 
- 15:45­16:00,  Break/ Room change 
- 16:00­16:30, Expert Session: Digital Transformation and Innovation for BBC News Robert McKenzie, Editor, BBC News Labs (TBC)
- 16:30­17:30, Panel: ​New challenges: from online to mobile (in Spanish, with an English interpretation)  
 - Nacho Cardero, ElConfidencial
 - María Ramírez, Elespanol.com
 - Fernando Berlín, radiocable.com
 - Juan Luis Sanchez, eldiario.es
 - Moderator: Dani Seseña, Cámara Abierta TVE 

* Mayo
** IV Jornadas Periodismo Datos #JPD16
- Cuándo: <2016-05-05 jue>--<2016-05-07 sáb>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://periodismodatos.okfn.es

#+BEGIN_HTML
<div itemscope itemtype="http://schema.org/Event">
<a itemprop="url" href="http://periodismodatos.okfn.es"><div itemprop="name"><strong>Data Journalism Conference</strong></div>
</a>
<div itemprop="description">Spanish Data Journalism and Open Data Conference</div>
<div><meta itemprop="startDate" content="2016-05-05T12:00">Starts: 05/05/2016 12:00PM</div>
<meta itemprop="endDate" content="2016-05-08:00.000">Ends: 2016-05-08:00.000
</div>
<div itemprop="location" itemscope itemtype="http://schema.org/PostalAddress">
<div itemprop="streetAddress">Calle Alameda 15</div>
<div><span itemprop="addressLocality">Madrid</span>, <span itemprop="addressRegion">Madrid</span></div><div itemprop="postalCode">28014</div>
<div itemprop="addressCountry">Spain</div>
</div>
#+END_HTML

** News Impact Summit London
- Cuándo: <2016-05-12 jue>
- Dónde: Londres, Reino Unido
- URL: http://newsimpact.io
- Fuente: http://ejc.net/projects/news/article/ejc-announces-a-new-series-of-news-impact-summits-in-2016

** Reunión GNOME Hispano
- Cuándo: <2016-05-16 lun 18:30-20:45>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/gnome-hispano
** I Congreso Iberoamericano Nebrija PIATCOM: tendencias, competencias y perfiles profesionales en el sector de la comunicación
- Call for Abstracts DEADLINE: <2016-03-13 dom>
- Cuándo: <2016-05-24 mar>--<2016-05-25 mié>
- Dónde: Universidad Nebrija. Facultad de Ciencias de la Comunicación. Campus de la Berzosa. Hoyo del Manzanares. Madrid
- Mapa: http://www.openstreetmap.org/relation/346078#map=17/40.59978/-3.94578
- URL: http://www.congresopiatcom.com/
** Jornadas SIG Libre
+ Call for Abstracts DEADLINE: <2016-03-13 dom>
+ Cuándo: <2016-05-24 mar>--<2016-05-29 dom>
+ Dónde: Aulas de Informática, Facultad de Letras (Universitat de Girona)
+ Mapa: 
+ URL: http://www.sigte.udg.edu/jornadassiglibre/jornadas-sig-libre/talleres/

Las Jornadas de SIG Libre son un evento de referencia en el sector de las tecnologías libres en el ámbito de la información geográfica. Son un punto de encuentro donde compartir conocimientos, experiencias y crear sinergias. El idioma de la conferencia es el Español.

 
La International QGIS User and Developer Conference quiere convertirse en el espacio de referencia, y un punto de encuentro para la familia de usuarios y desarrolladores que orbitan alrededor del proyecto QGIS, con el objetivo de recopilar experiencias y compartir el conocimiento sobre QGIS. El idioma de la conferencia es el Inglés.


** News Impact Summit Doha
- Cuándo: <2016-05-30 lun>
- Dónde: Doha, Qatar
- URL: http://newsimpact.io
- Fuente: http://ejc.net/projects/news/article/ejc-announces-a-new-series-of-news-impact-summits-in-2016

* Junio
** ICA Fukuoka 2016, conference of the International Communication Association
- Cuándo: <2016-06-09 jue>--<2016-06-13 lun>
- Dónde: Fukuoka, Japón
- Mapa: 
- URL: http://icahdq.org
** GEN Summit
- Cuándo: <2016-06-15 mié>--<2016-06-17 vie>
- Dónde: Viena, Austria
- Mapa: 
- URL: http://www.gensummit2016.org/

How can the media industry deal with Facebook, Apple, Google, Amazon and other mega-platforms offering news to their users? This is the major question for 2016 and the sixth annual GEN Summit will explore the most relevant solutions for your newsroom. Over-the-top platforms claim to want to partner with media organisations and share revenue, but who will own the data and the readers’ loyalty? Content distribution is becoming a common battleground for legacy media and pure online players alike. For the first time, both are facing the same struggle. Join more than 600 Editors-in-Chief and media innovators for three days in Vienna, presented by the Global Editors Network, June 15-17, 2016.
** Data Journalism Awards
   DEADLINE: <2016-04-10 dom>
- Cuándo: <2016-06-17 vie>
- Dónde: Viena, Austria
- Mapa: 
- URL: http://www.globaleditorsnetwork.org/programmes/data-journalism-awards/

Estos son los únicos premios mundiales que reconocen y ayudan a visibilizar la labor periodística que combina la visualización y el análisis de datos para narrar historias innovadoras. Entre los ganadores de anteriores ediciones de se encuentran The New York Times, ProPublica, The Guardian o La Nación (de Argentina). La fecha límite para presentar los proyectos es el 10 de abril a media noche (horario del Meridiano de Greenwich) y la cuantía de los premios es €1.000. Los premios #DJA2016 están orientados a redacciones y periodistas de organizaciones y grupos editoriales de cualquier tamaño, tanto grandes como pequeños. Se reconocen a los mejores trabajos en 12 categorías, incluyendo:

- Mejor trabajo de visualización de datos 
- Mejor investigación 
- Mejor app de datos aplicada al periodismo 
- Mejor web de periodismo de datos 
- Mejor portfolio individual 
- Mejor uso de datos en una noticia de última hora 
- Premio a datos abiertos 
- Premio de excelencia (premio del jurado y premio del público) 

El concurso está organizado por Global Editors Network, una plataforma que cuenta con el apoyo de Google y Knight Foundation y que aglutina jefes de redacción e innovadores en medios de comunicación comprometidos con el periodismo de alta calidad.
** Reunión GNOME Hispano
- Cuándo: <2016-06-20 lun 18:30-20:45>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/gnome-hispano 

* Julio
** News Impact Summit Berlin
- Cuándo: <2016-07-01 vie>
- Dónde: Berlín, Alemania
- URL: http://newsimpact.io
- Fuente: http://ejc.net/projects/news/article/ejc-announces-a-new-series-of-news-impact-summits-in-2016

** SIGIR 2016
<2016-07-17 dom>--<2016-07-21 jue>

39th International ACM SIGIR Conference on Research and Development in Information Retrieval, exactly 30 years since SIGIR 1986, also held in Pisa.

Researchers, academics, students, and industry leaders working in the broad area of information retrieval, are invited to join the conf for a rich, five-days program featuring full paper presentations, poster presentations, system demonstrations, tutorials, specialized workshops, an industry-oriented event, and social events.

The SIGIR conference is the major international forum for the presentation of new research results and for the demonstration of new systems and techniques in the field of information retrieval (IR). The General Chairs and Program Chairs of SIGIR 2016 invite all those working in areas related to IR to submit high-impact original papers for review. SIGIR 2016 welcomes contributions related to any aspect of IR theory, foundations, techniques, and applications, and solicits proposals for workshops, demonstrations, tutorials, and industry-oriented papers.

http://sigir.org/sigir2016/

** Reunión GNOME Hispano
- Cuándo: <2016-07-18 lun 18:30-20:45>
- Dónde: Medialab-Prado, Alameda 15, 28014, Madrid
- Mapa: http://www.openstreetmap.org/way/219016719#map=19/40.41044/-3.69359
- URL: http://medialab-prado.es/article/gnome-hispano

** SRCCON
- Cuándo: <2016-07-28 jue>--<2016-07-29 vie>
- Dónde:  Pacific Northwest College of Art, Portland, Oregon, EE.UU.
- Mapa:
- URL: http://srccon.org/

SRCCON is a hands-on conference focused on the practical challenges news technology and data teams encounter every day. Active participation is at the center of SRCCON, and we work to make it an inclusive and welcoming event where people can feel comfortable jumping in to work on complex problems. We welcome participants from all fields—if you want to strengthen journalism online, we want you there.

* Octubre
** VII Congreso Internacional en Gobierno, Administración y Políticas Públicas
- Cuándo: <2016-10-03 lun>--<2016-10-05 mié>
- Dónde: 
- Mapa: 
- URL: http://www.gigapp.org/index.php/congreso/congreso-2016

“Construyendo una nueva cultura administrativa: políticas y gestión pública con la ciudadanía”
El Congreso Internacional en Gobierno, Administración y Políticas Públicas, organizado por el GIGAPP desde 2010, ha logrado constituirse en un Congreso anual de referencia en los temas de Gobierno, Administración y Políticas Públicas en Iberoamérica. La progresión del evento da cuenta del avance en cantidad y calidad del evento. Este evento es un espacio abierto pensado para presentar y debatir nuevas ideas y enfoques, experiencias e investigaciones de calidad y cultivar vínculos de colaboración y generación de redes de trabajo sobre los ejes temáticos en los que se enmarca. 
 
** IODC 2016
<2016-10-06 jue>--<2016-10-07 vie>
4ª Conferencia Internacional sobre Datos Abiertos
Objertivos globales, impacto local
#+BEGIN_HTML
<div itemscope itemtype="http://schema.org/Event">
<a itemprop="url" href="http://opendatacon.org/"><div itemprop="name"><strong>International Open Data Conference</strong></div>
</a>
<div itemprop="description">Global goals, local impact. #iodc16</div>
<div><meta itemprop="startDate" content="2016-10-06T12:00">Starts: 10/06/2016 12:00PM</div>
<meta itemprop="endDate" content="2016-10-07:00.000">Ends: 2016-10-07:00.000
</div>
<div itemprop="location" itemscope itemtype="http://schema.org/PostalAddress">
<div><span itemprop="addressLocality">Madrid</span>, <span itemprop="addressRegion">Madrid</span></div><div itemprop="addressCountry">Spain</div>
</div>
#+END_HTML
http://opendatacon.org/

** Big Data Week
#+BEGIN_HTML
<div itemscope itemtype="http://schema.org/Event">
<a itemprop="url" href="http://london.bigdataweek.com/"><div itemprop="name"><strong>Big Data Week</strong></div>
</a>
<div itemprop="description">A global festival of Data</div>
<div><meta itemprop="startDate" content="2016-10-27T10:00">Starts: 27/10/2016 10:00AM</div>
<meta itemprop="endDate" content="2016-10-27:12.000">Ends: 2016-10-27:00.000
</div>
<div itemprop="location" itemscope itemtype="http://schema.org/PostalAddress">
<div><span itemprop="addressLocality">Londres</span>, <span itemprop="addressRegion">Londres</span></div><div itemprop="addressCountry">Reino Unido</div>
</div>
#+END_HTML
- Cuándo: <2016-10-27 jue>
- Dónde: etc.venues 155 Bishopsgate, Londres, Reino Unido
- Mapa: 51.5186567,-0.08028590000003533
- URL: http://london.bigdataweek.com/

Big data players from finance, healthcare & insurance, retail, IoT, entertainment, and travel are coming together for one week full of events.
Learn from industry leaders, attend meet-ups, webinars, workshops and discuss the latest developments in the big data world.

* Todo el año
* Becas
** Becas El País y Amazon para festival internacional de Periodismo de Perugia
- Cuándo: <2016-02-16 mar>--<2016-03-04 vie>
- Fecha límite:   DEADLINE: <2016-03-04 vie>
- URL: http://politica.elpais.com/politica/2016/02/15/actualidad/1455539561_487834.html

Los participantes deben escribir un ensayo sobre el periodismo en la era digital
Los premiados ganarán un viaje al Festival Internacional de Periodismo de Perugia

** Premios de periodismo
http://gijn.org/2015/06/08/premios-para-periodistas-de-investigacion/

* Cursos

* ProPublica's Summer Data Institute
  DEADLINE: <2016-03-31 jue>
First-ever Summer Data Institute, a 10-day intensive workshop on how to use data, design and code for journalism. The workshop will be from June 1st to 15th in our NYC offices. The deadline to apply is March 31st.

https://projects.propublica.org/graphics/summer
https://www.propublica.org/nerds/item/propublica-summer-data-institute

* Ideas

** Calendario en Google
** Calendario en ICS
** Tinyletter
** Schema.org
** Orgmode


